# Generated by Django 5.2.5 on 2025-08-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionoption',
            old_name='text',
            new_name='option_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='questionoption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
